/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketRouteRouteImport } from './routes/market/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as MarketFavoritesRouteImport } from './routes/market/favorites'
import { Route as MarketBrowseRouteImport } from './routes/market/browse'
import { Route as MarketAuthRouteImport } from './routes/market/auth'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as MarketProductProductIdRouteImport } from './routes/market/product.$productId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedSessionsSessionIdReviewRouteImport } from './routes/_authenticated/sessions.$sessionId.review'
import { Route as AuthenticatedSessionsSessionIdNewProductRouteImport } from './routes/_authenticated/sessions.$sessionId.new-product'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRouteRoute = MarketRouteRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketFavoritesRoute = MarketFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketBrowseRoute = MarketBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketAuthRoute = MarketAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MarketRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MarketProductProductIdRoute = MarketProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => MarketRouteRoute,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedSessionsSessionIdReviewRoute =
  AuthenticatedSessionsSessionIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)
const AuthenticatedSessionsSessionIdNewProductRoute =
  AuthenticatedSessionsSessionIdNewProductRouteImport.update({
    id: '/new-product',
    path: '/new-product',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market': typeof MarketRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/market/auth': typeof MarketAuthRoute
  '/market/browse': typeof MarketBrowseRoute
  '/market/favorites': typeof MarketFavoritesRoute
  '/market/': typeof MarketIndexRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/market/product/$productId': typeof MarketProductProductIdRoute
  '/sessions/$sessionId/new-product': typeof AuthenticatedSessionsSessionIdNewProductRoute
  '/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/market/auth': typeof MarketAuthRoute
  '/market/browse': typeof MarketBrowseRoute
  '/market/favorites': typeof MarketFavoritesRoute
  '/market': typeof MarketIndexRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/market/product/$productId': typeof MarketProductProductIdRoute
  '/sessions/$sessionId/new-product': typeof AuthenticatedSessionsSessionIdNewProductRoute
  '/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/market': typeof MarketRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/market/auth': typeof MarketAuthRoute
  '/market/browse': typeof MarketBrowseRoute
  '/market/favorites': typeof MarketFavoritesRoute
  '/market/': typeof MarketIndexRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/market/product/$productId': typeof MarketProductProductIdRoute
  '/_authenticated/sessions/$sessionId/new-product': typeof AuthenticatedSessionsSessionIdNewProductRoute
  '/_authenticated/sessions/$sessionId/review': typeof AuthenticatedSessionsSessionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/market'
    | '/auth'
    | '/products'
    | '/sessions'
    | '/suppliers'
    | '/market/auth'
    | '/market/browse'
    | '/market/favorites'
    | '/market/'
    | '/products/$productId'
    | '/sessions/$sessionId'
    | '/market/product/$productId'
    | '/sessions/$sessionId/new-product'
    | '/sessions/$sessionId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/products'
    | '/sessions'
    | '/suppliers'
    | '/market/auth'
    | '/market/browse'
    | '/market/favorites'
    | '/market'
    | '/products/$productId'
    | '/sessions/$sessionId'
    | '/market/product/$productId'
    | '/sessions/$sessionId/new-product'
    | '/sessions/$sessionId/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/market'
    | '/auth'
    | '/_authenticated/products'
    | '/_authenticated/sessions'
    | '/_authenticated/suppliers'
    | '/market/auth'
    | '/market/browse'
    | '/market/favorites'
    | '/market/'
    | '/_authenticated/products/$productId'
    | '/_authenticated/sessions/$sessionId'
    | '/market/product/$productId'
    | '/_authenticated/sessions/$sessionId/new-product'
    | '/_authenticated/sessions/$sessionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketRouteRoute: typeof MarketRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/favorites': {
      id: '/market/favorites'
      path: '/favorites'
      fullPath: '/market/favorites'
      preLoaderRoute: typeof MarketFavoritesRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/browse': {
      id: '/market/browse'
      path: '/browse'
      fullPath: '/market/browse'
      preLoaderRoute: typeof MarketBrowseRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/auth': {
      id: '/market/auth'
      path: '/auth'
      fullPath: '/market/auth'
      preLoaderRoute: typeof MarketAuthRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/market/product/$productId': {
      id: '/market/product/$productId'
      path: '/product/$productId'
      fullPath: '/market/product/$productId'
      preLoaderRoute: typeof MarketProductProductIdRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/sessions/$sessionId/review': {
      id: '/_authenticated/sessions/$sessionId/review'
      path: '/review'
      fullPath: '/sessions/$sessionId/review'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdReviewRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
    '/_authenticated/sessions/$sessionId/new-product': {
      id: '/_authenticated/sessions/$sessionId/new-product'
      path: '/new-product'
      fullPath: '/sessions/$sessionId/new-product'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdNewProductRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedSessionsSessionIdRouteChildren {
  AuthenticatedSessionsSessionIdNewProductRoute: typeof AuthenticatedSessionsSessionIdNewProductRoute
  AuthenticatedSessionsSessionIdReviewRoute: typeof AuthenticatedSessionsSessionIdReviewRoute
}

const AuthenticatedSessionsSessionIdRouteChildren: AuthenticatedSessionsSessionIdRouteChildren =
  {
    AuthenticatedSessionsSessionIdNewProductRoute:
      AuthenticatedSessionsSessionIdNewProductRoute,
    AuthenticatedSessionsSessionIdReviewRoute:
      AuthenticatedSessionsSessionIdReviewRoute,
  }

const AuthenticatedSessionsSessionIdRouteWithChildren =
  AuthenticatedSessionsSessionIdRoute._addFileChildren(
    AuthenticatedSessionsSessionIdRouteChildren,
  )

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRouteWithChildren
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsSessionIdRoute:
    AuthenticatedSessionsSessionIdRouteWithChildren,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketRouteRouteChildren {
  MarketAuthRoute: typeof MarketAuthRoute
  MarketBrowseRoute: typeof MarketBrowseRoute
  MarketFavoritesRoute: typeof MarketFavoritesRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MarketProductProductIdRoute: typeof MarketProductProductIdRoute
}

const MarketRouteRouteChildren: MarketRouteRouteChildren = {
  MarketAuthRoute: MarketAuthRoute,
  MarketBrowseRoute: MarketBrowseRoute,
  MarketFavoritesRoute: MarketFavoritesRoute,
  MarketIndexRoute: MarketIndexRoute,
  MarketProductProductIdRoute: MarketProductProductIdRoute,
}

const MarketRouteRouteWithChildren = MarketRouteRoute._addFileChildren(
  MarketRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketRouteRoute: MarketRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
